[package]
name = "mike"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1.0"
bs62 = "0.1.4"

[lib]
name = "mike"
proc-macro = true
